// fetch movies
export const MOVIE_FETCH_STARTED = 'POST_FETCH_STARTED';
export const MOVIE_FETCH_COMPLETED = 'POST_FETCH_COMPLETED';
export const MOVIE_FETCH_ERROR = 'POST_FETCH_ERROR';
export const MOVIE_FETCH_RESET = 'POST_FETCH_RESET';

// create movie
export const MOVIE_CREATE_STARTED = 'MOVIE_CREATE_STARTED';
export const MOVIE_CREATE_COMPLETED = 'MOVIE_CREATE_COMPLETED';
export const MOVIE_CREATE_ERROR = 'MOVIE_CREATE_ERROR';
export const MOVIE_CREATE_RESET = 'MOVIE_CREATE_RESET';

// get movie by id
export const MOVIE_GET_BY_ID_STARTED = 'MOVIE_GET_BY_ID_STARTED';
export const MOVIE_GET_BY_ID_COMPLETED = 'MOVIE_GET_BY_ID_COMPLETED';
export const MOVIE_GET_BY_ID_ERROR = 'MOVIE_GET_BY_ID_ERROR';
export const MOVIE_GET_BY_ID_RESET = 'MOVIE_GET_BY_ID_RESET';

// update movie
export const MOVIE_UPDATE_STARTED = 'MOVIE_UPDATE_STARTED';
export const MOVIE_UPDATE_COMPLETED = 'MOVIE_UPDATE_COMPLETED';
export const MOVIE_UPDATE_ERROR = 'MOVIE_UPDATE_ERROR';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';

// delete movie
export const MOVIE_DELETE_STARTED = 'MOVIE_DELETE_STARTED';
export const MOVIE_DELETE_COMPLETED = 'MOVIE_DELETE_COMPLETED';
export const MOVIE_DELETE_ERROR = 'MOVIE_DELETE_ERROR';
export const MOVIE_DELETE_RESET = 'MOVIE_DELETE_RESET';
