// create user
export const USER_CREATE_STARTED = 'USER_CREATE_STARTED';
export const USER_CREATE_COMPLETED = 'USER_CREATE_COMPLETED';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';
export const USER_CREATE_RESET = 'USER_CREATE_RESET';

// authentication USER
export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_COMPLETED = 'AUTHENTICATION_COMPLETED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_RESET = 'AUTHENTICATION_RESET';
